version: '{build}'

image:
  - Visual Studio 2013

configuration:
  - Release

install:
  - git submodule update --init --recursive

build:
  project: src\electromagnetic\electromagnetic.sln

artifacts:
  - path: 'src\electromagnetic\%CONFIGURATION%\electromagnetic.exe'
